### ISSUE TITLE
(Feature request) Add ability to pan

### ISSUE THREAD

**Issue by zehawki** [musama619/react-photo-editor#167]
This is a sweet editor. It could do with an important feature that's kind of intuitive today and without it, its a bit lacking - ability to pan the image. Since it has a zoom, without the ability to pan, its kind of useless.

Here's how the panning works with zoom: https://react-avatar-editor.netlify.app/

Would you please consider adding that? And then the next logical step is adding support for pinch to zoom.

**Comment by musama619** [comment]
Thank you for your suggestion! Adding panning is a good idea. I will check into it first and provide an update.

**Comment by musama619** [comment]
[v2.1.0](https://github.com/musama619/react-photo-editor/releases/tag/v2.1.0) added the feature.
Thanks @zehawki

**Comment by zehawki** [comment]
I checked this out in the stackblitz demo - when the save button is clicked, the image reverts to the original in the edit window... thats confusing or?
