### ISSUE TITLE
Saving image cause parent form submit

### ISSUE THREAD

**Issue by JosefSchovanec** [musama619/react-photo-editor#189]
Hello, i have this problem:

we are using PhotoEditor on some form. When i select image, editor is shown, and after clicking on Save button, parent form is submitted. It is unwanted behavior.

I belive this code

`<button
	className={modalHeaderButtonClasses}
	onClick={() => saveImage()}
	data-testid='save-button'
	>
	  Save
</button>`

should be changed to

`<button
	className={modalHeaderButtonClasses}
	onClick={(e) =>{
                   e.preventDefault();
                   saveImage();
}
}
	data-testid='save-button'
	>
	  Save
</button>`

This should be enought to prevent submitting parent form...

Thank you

**Comment by musama619** [comment]
Hello, Thank you for reporting this issue with a solution. It is fixed in [v2.1.4-rc.2](https://www.npmjs.com/package/react-photo-editor/v/2.1.4-rc.2). I went for less code way and added `type='button'` in all the buttons, that were causing this issue.

**Comment by JosefSchovanec** [comment]
@musama619 It works, thank you

**Comment by JosefSchovanec** [comment]
Closing as solved.
